# make_municipality_table.py
# Appendix table: estimated EV charger penetration per municipality (tau = 0.90),
# RF vs XGBoost, rendered as a "folded" longtable: the alphabetical list is
# split in half and the two halves sit side by side (8 physical columns), so
# the table reads in two columns while remaining a single centered longtable
# that can break across pages.
#
# (A multicols layout was tried first, but each half-tabular is an unbreakable
# block taller than the text column, which wrecks balancing and centering.)
#
# Output: ../results/municipal_penetration_table.tex
# Overleaf preamble needs: \usepackage{longtable}, \usepackage{booktabs}
#
# Usage:
#   python make_municipality_table.py                 # tau = 0.90

import argparse
from pathlib import Path

import pandas as pd

# anchor paths to this file so the script works from any working directory
ROOT = Path(__file__).resolve().parent.parent   # MSc-Thesis/
DATA_DIR = ROOT / "data"
RESULTS_DIR = ROOT / "results"

HEADER = "Municipality & Meters & RF (\\%) & XGB (\\%)"


def build_table(threshold: int) -> pd.DataFrame:
    col = f"n_evs_p{threshold}"
    kom = pd.read_csv(DATA_DIR / "KOM.txt", sep=";").set_index("KOM")["KOM_T"]
    rf = pd.read_csv(DATA_DIR / "rf_EV_area_distr.csv").set_index("KOM")
    xgb = pd.read_csv(DATA_DIR / "xgb_EV_area_distr.csv").set_index("KOM")
    t = pd.DataFrame({
        "name": kom,
        "meters": rf["n_meters"],
        "rf": (rf[col] / rf["n_meters"] * 100).round(2),
        "xgb": (xgb[col] / xgb["n_meters"] * 100).round(2),
    }).dropna().sort_values("name")
    t["meters"] = t["meters"].astype(int)
    return t


def fmt(row) -> str:
    if row is None:
        return " & & &"
    return (f"{row['name']} & {row['meters']:,} & "
            f"{row['rf']:.2f} & {row['xgb']:.2f}")


def main(threshold: int):
    t = build_table(threshold)
    half = (len(t) + 1) // 2
    left, right = t.iloc[:half], t.iloc[half:]

    rows = "\n".join(
        f"    {fmt(left.iloc[i])} & "
        f"{fmt(right.iloc[i] if i < len(right) else None)} \\\\"
        for i in range(half)
    )

    tex = (
        "% Auto-generated by make_municipality_table.py -- do not edit by hand.\n"
        "% Requires in the preamble: \\usepackage{longtable}, \\usepackage{booktabs}\n"
        "\\begingroup\\small\n"
        "\\setlength{\\tabcolsep}{3pt}\n"
        "% longtable is left-aligned by default; stretch both margins to centre it\n"
        "\\setlength{\\LTleft}{\\fill}\n"
        "\\setlength{\\LTright}{\\fill}\n"
        "\\begin{longtable}{lrrr@{\\hspace{1.5em}}lrrr}\n"
        "\\caption{Estimated EV charger penetration at "
        f"$\\tau={threshold/100:.2f}$ per municipality, 2024.}}\n"
        "\\label{tab:app_municipal_penetration}\\\\\n"
        "\\toprule\n"
        f"{HEADER} & {HEADER} \\\\\n"
        "\\midrule\n"
        "\\endfirsthead\n"
        "\\caption[]{Estimated EV charger penetration at "
        f"$\\tau={threshold/100:.2f}$ per municipality, 2024 (continued).}}\\\\\n"
        "\\toprule\n"
        f"{HEADER} & {HEADER} \\\\\n"
        "\\midrule\n"
        "\\endhead\n"
        "\\bottomrule\n"
        "\\endfoot\n"
        f"{rows}\n"
        "\\end{longtable}\n"
        "\\endgroup\n"
    )
    out = RESULTS_DIR / "municipal_penetration_table.tex"
    out.write_text(tex, encoding="utf-8")
    print(f"saved {out}  ({len(t)} municipalities, folded at {half})")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--threshold", type=int, default=90,
                    choices=[50, 70, 80, 90])
    args = ap.parse_args()
    main(args.threshold)
